### PR TITLE
Conversion to cookiecutter template

### PR DESCRIPTION
**Pull request by fcollonval**
@jonmmease here comes the first cookiecutter template version 😃

### CODE REVIEW

**Comment by jonmmease** [comment]
Hi @fcollonval , sorry for the delay on my part.  I haven't tested this yet but it looks great!

One thought though, I'm not sure if I want to end up maintaining the cookie cutter template here. Perhaps we should reach out to the jupyter team to see if they'd be interested in having this under their umbrella. 

What do you think?

**Comment by fcollonval** [comment]
Hi @jonmmease, 
I totally understand your point of view. I'll ping the jupyter team through [gitter](https://gitter.im/jupyterlab/jupyterlab) to get their feedbacks.

**Comment by fcollonval** [comment]
Hey @jonmmease,
I did not get answer from the Jupyter team. If you want you can raise me as contributor, so I'll close this PR and help you with maintenance. It seems this solution is not receiving big attention anyway - although it's a must for my use case.

**Comment by jonmmease** [comment]
Thanks for following up @fcollonval, this sounds good.  I've added you to the repo, merge away! 🙂

**Pull request merged**
